<?php
/*
 * Poker League Manager: A Drupal module to manage our poker league
 * Todo:
 * - Fix current payout structure, add editor for payouts
 * - Menu for navigating within module
 *   - Main Page
 *     - Recent News (results, announcements)
 *   - Blocks
 *     - Leaderboard, Last Results, Next Game
 *   - Players
 *     - list all, browse 
 *   - Results (browse past games, other seasons)
 *     - games listed under plm/events/%event because we don't want to need
 *       the sid AND the eid.  Once we load the event, 
 *       we have sid and so we can either rewrite breadcrumbs,
 *       or use a custom seasons browsing menu or selector...investigate ?destination=xxx...
 *   - Schedule (upcoming games)
 *   - Current Standings

 * - Handle final table  - Accumulate rakes?
 * - Publish game results when done (custom node type?)
 *   - send email to list
 *   - Allow comments, messages to admin
 * - Permissions
 *   - Hide money stats from non-verified users
 *   - Tie user accounts to player ids
 * - Theming (make it purty)
 */


require_once drupal_get_path('module', 'plm') .'/plm.inc';
require_once drupal_get_path('module', 'plm') .'/plm_db.inc';
require_once drupal_get_path('module', 'plm') .'/plm_tablesort.inc';

function plm_menu() {
  $items = array();

  $items['plm'] = array(
    'title' => 'Roker League (PLM)',
    'page callback' => 'plm_main',
    'access arguments' => array('access poker league content'),
    'description' => t('Poker League'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'plm',
  );
  $items['plm/seasons'] = array(
    'title' => t('Seasons'),
    'description' => 'Browse Seasons',
    'page callback' => 'plm_seasons_list',
    'page arguments' => array(NULL),
    'access arguments' => array('access poker league content'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
  );
  $items['plm/seasons/list'] = array(
    'title'  => t('List Seasons'),
    'weight' => -1,
    'type'   => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['plm/seasons/new'] = array(
    'title' => t('New Season'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_season_form', 'new'),
    'access arguments' => array('administer poker league'),
    //'type' => MENU_NORMAL_ITEM,
    'type' => MENU_LOCAL_TASK,
    'file' => 'plm_admin.inc',
    'weight' => 0,
  ); 

  $items['plm/seasons/%plm_season'] = array(
    'title' => t('View Season'),
/*     'title callback' => 'plm_season_title', */
/*     'title_arguments' => array(3), */
    'description' => 'View a poker season',
    'page callback' => 'plm_season_view',
    'page arguments' => array(2),
    'access arguments' => array('access poker league content'),
    //'type' => MENU_NORMAL_ITEM,
    //'type' => MENU_LOCAL_TASK,
    //'type' => MENU_CALLBACK,
  );
  $items['plm/seasons/%plm_season/view'] = array(
    'title'  => t('View'),
    'weight' => -1,
    'type'   => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['plm/seasons/%plm_season/edit'] = array(
    'title' => t('Edit'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_season_form', 2),
    'access arguments' => array('administer poker league'),
    //'type' => MENU_NORMAL_ITEM,
    'type' => MENU_LOCAL_TASK,
    'file' => 'plm_admin.inc',
  ); 
  $items['plm/seasons/%plm_season/delete'] = array(
    'title' => t('Delete'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_season_confirm_delete', 2),
    'access arguments' => array('administer poker league'),
    //'type' => MENU_NORMAL_ITEM,
    'type' => MENU_LOCAL_TASK,
    'file' => 'plm_admin.inc',
  ); 
  $items['plm/seasons/%plm_season/standings'] = array(
    'title' => t('Standings'),
    'description' => 'View the current standings for this season.',
    'page callback' => 'plm_standings',
    'page arguments' => array(2),
    'access arguments' => array('access poker league content'),
    //'type' => MENU_NORMAL_ITEM,
    'type' => MENU_LOCAL_TASK,
  );
  $items['plm/seasons/%plm_season/newevent'] = array(
    'title' => 'New Event',
    'description' => 'Set up a new event',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_event_form',  NULL, 2),
    'access arguments' => array('administer poker league'),
    //'type' => MENU_NORMAL_ITEM,
    'type' => MENU_LOCAL_TASK,
    'file' => 'plm_admin.inc',
  );
  $items['plm/events/%plm_event'] = array(
    'title' => t('Event'),
    'description' => 'View the details of a poker event',
    'page callback' => 'plm_event_view',
    'page arguments' => array(2),
    'access arguments' => array('access poker league content'),
    'type' => MENU_NORMAL_ITEM,
//    'type' => MENU_CALLBACK,
  );
  $items['plm/events/%plm_event/view'] = array(
    'title'  => t('View'),
    'weight' => -1,
    'type'   => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['plm/events/%plm_event/edit'] = array(
    'title' => t('Edit'),
    'description' => 'Edit the details of a poker event',
    'page callback' => 'plm_event_form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_event_form', 2),
    'access arguments' => array('administer poker league'),
    //'type' => MENU_NORMAL_ITEM,
    'type' => MENU_LOCAL_TASK,
    'file' => 'plm_admin.inc',
  );
  $items['plm/players'] = array(
    'title' => t('Players'),
    'description' => 'Browse Players',
    'page callback' => 'plm_players_list',
    'access arguments' => array('access poker league content'),
    'type' => MENU_NORMAL_ITEM,
    //'type' => MENU_LOCAL_TASK,
  );
  $items['plm/players/list'] = array(
    'title'  => t('List Players'),
    'weight' => -1,
    'type'   => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['plm/players/new'] = array(
    'title' => t('Add Player'),
    'description' => 'Add a New Player',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_player_form'),
    'access arguments' => array('administer poker league'),
    //'type' => MENU_NORMAL_ITEM,
    'type' => MENU_LOCAL_TASK,
    'file' => 'plm_admin.inc',
  );
  $items['plm/players/pid/%plm_player'] = array(
    'title' => t('Player'),
    'description' => 'Show player details',
    'page callback' => 'plm_player_view',
    'page arguments' => array(3),
    'access arguments' => array('access poker league content'),
    'type' => MENU_NORMAL_ITEM,
    //'type' => MENU_LOCAL_TASK,
    //    'type' => MENU_CALLBACK,
  );
  $items['plm/players/pid/%plm_player/edit'] = array(
    'title' => t('Edit Player'),
    'description' => 'Edit player details',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_player_form', 3),
    'access arguments' => array('administer poker league'),
    'type' => MENU_LOCAL_TASK,
//    'type' => MENU_CALLBACK,
    'file' => 'plm_admin.inc',
  );
 $items['plm/players/pid/%plm_player/delete'] = array(
    'title' => t('Delete Player'),
    'description' => 'Delete player from the roster',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_player_confirm_delete', 3),
    'access arguments' => array('administer poker league'),
    'type' => MENU_LOCAL_TASK,
//    'type' => MENU_CALLBACK,
    'file' => 'plm_admin.inc',
  );
 $items['plm/results/%plm_result/%/edit'] = array(
   'title' => t('Edit Result'),
   'description' => 'Edit result',
   'load arguments' => array(3),
   'page callback' => 'drupal_get_form',
   'page arguments' => array('plm_result_form', 2),
   'access arguments' => array('administer poker league'),
   'file' => 'plm_admin.inc',
   //'type' => MENU_NORMAL_ITEM,
   'type' => MENU_CALLBACK,
 );
 $items['plm/results/%plm_result/%/delete'] = array(
   'title' => t('Delete Result'),
   'description' => 'Delete result from the league record',
   'load arguments' => array(3),
   'page callback' => 'drupal_get_form',
   'page arguments' => array('plm_result_confirm_delete', 2),
   'access arguments' => array('administer poker league'),
   ///'type' => MENU_NORMAL_ITEM,
   'type' => MENU_CALLBACK,
   'file' => 'plm_admin.inc',
 );

  // Admin Menu Items

  $items['admin/plm'] = array(
    'title' => 'Poker League (PLM)',
    'description' => 'Set up and run a poker league',
    'page callback' => 'plm_admin',
    'access arguments' => array('administer poker league'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -11,
    'file' => 'plm_admin.inc',
  );  
  $items['admin/plm/settings'] = array(
    'title' => 'Settings',
    'description' => 'General settings for poker league',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plm_settings'),
    'access arguments' => array('administer poker league'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'plm_admin.inc',
  );

/*   $items['admin/plm/seasons'] = array( */
/*     'title' => t('Seasons'), */
/*     'description' => 'Manage Seasons', */
/*     'page callback' => 'plm_seasons_list', */
/*     'page arguments' => array(NULL), */
/*     'access arguments' => array('administer poker league'), */
/*     'type' => MENU_NORMAL_ITEM, */
/*     //'file' => 'plm_admin.inc', */
/*   ); */
  
/*   $items['admin/plm/seasons/list'] = array( */
/*     'title'  => t('List Seasons'), */
/*     'weight' => -1, */
/*     'type'   => MENU_DEFAULT_LOCAL_TASK, */
/*   ); */
  
/*   $items['admin/plm/seasons/new'] = array( */
/*     'title' => t('New Reason'), */
/*     'page callback' => 'drupal_get_form', */
/*     'page arguments' => array('plm_season_form'), */
/*     'access arguments' => array('administer poker league'), */
/*     'type' => MENU_LOCAL_TASK, */
/*     'file' => 'plm_admin.inc', */
/*     'weight' => 0, */
/*   );  */
/*   $items['admin/plm/seasons/%sid/edit'] = array( */
/*     'title' => t('Edit Season'), */
/*     'page callback' => 'drupal_get_form', */
/*     'page arguments' => array('plm_season_form',  5), */
/*     'access arguments' => array('administer poker league'), */
/*     'type' => MENU_CALLBACK, */
/*     'file' => 'plm_admin.inc', */
/*   );  */
/*   $items['admin/plm/seasons/%sid/delete'] = array( */
/*     'title' => 'Delete Season', */
/*     'page callback' => 'drupal_get_form', */
/*     'page arguments' => array('plm_season_delete_confirm', 3), */
/*     'access arguments' => array('administer poker league'), */
/*     'file' => 'plm_admin.inc', */
/*     'type' => MENU_CALLBACK, */
/*   ); */


  return $items;
  
}

function plm_menu_alter(){

}

function plm_perm() {
  return array('access poker league content', 'administer poker league');
}

// implementation of hook_access()
function plm_access($op, $node, $account) {
  if ($op == 'create' || $op == 'update' || $op == 'delete') {
    return user_access('administer poker league', $account);
  }
  if ($op == 'view') {
    if (user_access('access poker league content', $account) )
      return TRUE;
  }
  return FALSE;
}

function plm_event_access($op, $node, $account) {
  if ($op == 'create' || $op == 'update' || $op == 'delete') {
    return user_access('administer poker league', $account);
  }
  if ($op == 'view') {
    if (user_access('access poker league content', $account) )
      return TRUE;
  }
  return FALSE;
}

function plm_main() {
  $content .= "<p>Poker League Manager Main Page</p>";
  $items = plm_menu();
  $content .= '<dl class="admin-list">';
  foreach ( $items as $path => $menu ) {
    $t = explode('/', $path);
    if ( count($t) == 2 ) {
      if (($t[0] == 'plm' ) 
          && $menu['type'] == MENU_NORMAL_ITEM) {
        $content .= '<dt>'. l($menu['title'], $path) .'</dt>';
        if ( isset($menu['description']) ) {
          $content .= '<dd>'. $menu['description'] .'</dd>';
        }
      }
    }
  }
  $content .= "</dl>";
  print theme('page', $content);

}

function plm_standings($plm_season) {
  drupal_set_title("$plm_season->title Standings");
  
  $header = array(
    array('data' => t('Rank')),
    array('data' => t('Name')),
    array('data' => t('Points')),
    array('data' => t('Winnings')),
    array('data' => t('Places')),
  );
  $sid = $plm_season->sid;
  $players = _get_plm_standings($sid);
  if (!$players) {
    $output .= '<p>No Results Found</p>';
    return $output;
  }
  $rank = 1;
  foreach ($players as $rec) {
    $rowdata = array(
      $rank,      
      l(t($rec->name), 'plm/players/pid/' . $rec->pid),
      $rec->points,
      $rec->cash ? '$' . $rec->cash : '',
      $rec->places ? $rec->places : '',
    );
    $rank++;
    $rows[] = $rowdata;
  }
  $caption = $plm_season->title;
  return $output . _theme_plm_table($header, $rows, $attr, $caption);
  //print theme('page', $content);
}

/* function plm_season_title($plm_season) { */
/*   //print_r('DEBUG: Season: (' . $plm_season . ')'); */
/*   return $plm_season->title; */
/* } */

function plm_player_load($pid) {
  return _get_plm_player($pid);
}

function plm_players_list() {
  $output = '';
  drupal_set_title("Poker Players");

  $num_players = _get_num_plm_players();
  $output .= format_plural($num_players, '1 Player', '@count Players');

  $header = array(
    array('data' => t('Name'),     'field' => 'name'   ),
    array('data' => t('Points'),   'field' => 'points', 'sort' => 'desc', 
          'default' => 1),
    array('data' => t('Winnings'), 'field' => 'cash', 'sort' => 'desc'   ),
    array('data' => t('Places'),   'field' => 'places', 'sort' => 'desc' ),
  );
  if (user_access('administer poker league')) {
    $header[] = array('data' => t(''), 'colspan' => 2);
  }
  $players = _get_plm_players(plm_tablesort_sql($header));

  foreach ($players as $rec) {
    $rowdata = array(
      l(t($rec->name), 'plm/players/pid/' . $rec->pid),
      $rec->points,
      $rec->cash ? '$' . $rec->cash : '',
      $rec->places ? $rec->places : '',
    );

    if (user_access('administer poker league')) {
      $rowdata[] = l(t('edit'), 'plm/players/pid/' . $rec->pid . '/edit');
      $rowdata[] = l(t('delete'), 'plm/players/pid/' . $rec->pid . '/delete');
    }
    $rows[] = $rowdata;
  }

  //return $output . theme('plm_table', $header, $rows);
  return $output . _theme_plm_table($header, $rows);
}

function plm_player_view($player) {
  drupal_set_title($player->name);
  //$output = "<p>Details of $player->name go here</p>\n";
  $output .= theme_plm_player_details($player);
  return $output;
}
function theme_plm_player_details($player) {

  $header = array(
    "Season",
    "Event",
    "Host",
    "Place", 
    "Points",
    "Winnings",    
  );
  $places = _get_plm_results_by_player($player->pid);
  $sid    = NULL;
  $s_points   = array();
  $s_cash     = array();
  $tot_points = 0;
  $tot_cash   = 0;
  //print_r('Hello' . $places);
  //print_r($player);
  foreach ($places as $r) {
    // Season Totals
    if ($sid && $sid != $r->sid){
      $rows[] = array(
        array('data' => t("Season $sid Total:"), 'colspan' => 4, 'class' => 'st_hdr'),
        array('data' => $s_points[$sid], 'class' => 'st_cell'), 
        array('data' => '$' . $s_cash[$sid], 'class' => 'st_cell'),
      );
      $tot_points += $s_points[$sid];
      $tot_cash   += $s_cash[$sid];
    }

    $rowdata = array(
      $r->sid,
      $r->title,
      $r->host,
      $r->place,
      $r->points,
      '$' . $r->cash,      
    );
    $rows[] = $rowdata;
    
    $sid       = $r->sid;
    $s_points[$sid] += $r->points;
    $s_cash[$sid]   += $r->cash;
  }
  // Last Season Total
  if ($sid){
    $rows[] = array(
      array('data' => t("Season $sid Total:"), 'colspan' => 4, 'class' => 'st_hdr'),
      array('data' => $s_points[$sid], 'class' => 'st_cell'), 
      array('data' => '$' . $s_cash[$sid], 'class' => 'st_cell'),
    );
    $tot_points += $s_points[$sid];
    $tot_cash   += $s_cash[$sid];
  }
  // Grand Total
  $rows[] = array(
    array('data' => t("Grand Total:"), 'colspan' => 4, 'class' => 'gt_hdr'),
    $tot_points, '$' . $tot_cash
  );
  
  $output .= theme('table', $header, $rows);
  return $output;
}
function plm_season_load($sid) {
  return _get_plm_season($sid);
}
//function plm_season_to_arg($s) {
//  return $s->sid;
//}

function plm_seasons_list() {
  //$output .= '<h5>plm_seasons_list()</h5>';
  drupal_set_title("Poker Seasons");
/*   $item = menu_get_item(); */
/*   foreach($item as $x => $y){ */
/*     print_r('<b>'); */
/*     print_r($x); */
/*     print_r('</b> =&gt; '); */
/*     print_r($y); */
/*     print_r('<br>'); */
/*   } */
  
  $seasons = _get_plm_seasons();
  if (!isset($seasons)){
    $output = "<p>There are no seasons configured</p>";
    return $output;
  }
  $list = array();
  $fmt = 'D, M j Y';
  foreach ($seasons as $s) {
    $datestr = format_date($s->start_date, 'custom', $fmt);
    if ($s->end_date) $datestr .= " to " . format_date($s->end_date, 'custom', $fmt);
    else $datestr = 'Started ' . $datestr;
    //$output .= "<p>item($s->title, $datestr)</p>";
    $list[] = l(t("$s->title"), 
                "plm/seasons/$s->sid") . "<div>$datestr</div>";
  }
  $output .= theme('item_list', $list);
  return $output;
}

function theme_plm_season($season, $teaser=NULL) {
  //$output .= t("<p>theme_plm_season()</p>");
  $output .= theme_plm_date_range($season, $teaser);
  $output .= theme_plm_event_list($season, $teaser);
  return $output;
}

function theme_plm_date_range($season, $teaser) {
  //$output = '<p>"theme_plm_date_range"</p>';
  $label = 'Starts';
  $now = gmmktime();
  if ($season->start_date < $now) $label = 'Started';
  $datestr = date('m-d-Y', $season->start_date);
  $output .= t(
    '<div>@label: @datestr</div>', array(
      '@label' => $label, 
      '@datestr' => $datestr,
    )
  );
  if ($season->end_date == 0) return $output;
  
  $label = 'Ends';
  if ($season->end_date < $now) $label = 'Ended';
  $datestr = date('m-d-Y', $season->end_date);
  $output .= t(
    '<div>@label: @datestr</div>',
    array(
      '@label' => $label, 
      '@datestr' => $datestr));
  return $output;// . "</div>";
}

function theme_plm_event_list($season, $teaser) {
  //$output = '<p>"theme_plm_event_list"</p>';
  $label = 'Events';
  $num_events = _get_num_plm_events($season->sid);
  $output .= "<div class=\"plm_event_list\">";
  $output .= "<div class=\"num_events\">$label: $num_events</div>";
  if ($num_events == 0 || $teaser) return $output . '</div>';

  $header = array('Event', 'Date', 'Host', 'Entries', '');
  if (user_access('administer poker league')) {
    $header[] = '';
  }
  
  $events = _get_plm_events($season->sid);
  
  foreach ($events as $event) {
    
    //$date_str = date("m-d-Y", $event->event_date);
    //$date_str = date("n/j/Y", $event->event_date);
    //$date_str = date("D, M j Y g:iA", $event->event_date);
    $date_str = date("D, M j Y", $event->event_date);
    $rowdata = array(
      l(t($event->title), "plm/events/$event->eid"),
      $date_str,
      $event->host,
      $event->num_players ? $event->num_players : '',
      $event->finished ? l(t('results'), "plm/events/$event->eid") : '',
    );
    if (user_access('administer poker league')) {
      $rowdata[] = l(t('edit'),
                     "plm/events/$event->eid/edit");
    }
    $rows[] = $rowdata;
  }

  $output .= theme('table', $header, $rows);
  $output .= "</div>\n";
  return $output;
}


function plm_current_season_view() {
  $season = _get_plm_current_season();
  return plm_season_view($season);
  
}
function plm_season_view($season) {
  //$output = "<h4>Season: $season->title</h4>";
  drupal_set_title("$season->title");
/*   $item = menu_get_item(); */
/*   foreach($item as $x => $y){ */
/*     print_r('<b>'); */
/*     print_r($x); */
/*     print_r('</b> =&gt; '); */
/*     print_r($y); */
/*     print_r('<br>'); */
/*   } */
  $output .= theme_plm_season($season);
  return $output;
}

function plm_seasons() {
  return '<p>plm_seasons()</p>' . plm_mainpage(null, null);
}


function plm_event_load($node) {
  return _get_plm_event($node);
}
function plm_event_view($event, $teaser = FALSE, $page = FALSE) {
  drupal_set_title("$event->title");
  $output = theme_plm_event_details($event);
  return $output;
}

function theme_plm_event_details($event) {
  $s = _get_plm_season($event->sid);
  $output .= theme_plm_event_season($s);
  $output .= theme_plm_event_date($event);
  $output .= theme_plm_event_host($event);
  if ($event->num_players){
    $output .= theme_plm_event_num_players($event);
    //$output .= "<div>Initial Pot: $event->pot_start</div>\n";
    //$output .= "<div>Buyin: $event->buyin</div>\n";
    $pot_total = $event->pot_start + $event->buyin * $event->num_players;
    $output .= "<div>Total Pot: \$$pot_total</div>\n";
    $output .= theme_plm_event_results($event);
  }
  return $output;
}
function theme_plm_event_date($event) {
  $label = 'Event Date';
  $datestr = date('m-d-Y', $event->event_date);
  $output .= "<div class=\"pl_event_date\">$label: $datestr</div>";
  return $output;
}
function theme_plm_event_host($event) {
  $label = 'Host';
  $rec = _get_plm_player($event->hid);
  $name = $rec->name;
  if (!$name) $name = 'None';
  $output = "<div class=\"event_host\">$label: $name</div>";
  return $output;
}
function theme_plm_event_num_players($event) {
  $label = 'Entries';
  $num_players = $event->num_players;
  $output = "<div class=\"num_players\">$label: $num_players</div>";
  return $output;
}
function theme_plm_event_season($season) {
  $label = 'Season';
  $title = $season->title;
  $output = "$label: " . l(t("@title", array('@title'=>$title)),
                           "plm/seasons/$season->sid");
  return $output;
}

function plm_result_load($eid, $place) {
  $res = _get_plm_result($eid, $place);
  if (!$res) $res = _plm_result_new($eid, $place);
  return $res;
}
// blank event result
function _plm_result_new($eid, $place) {
  $res->eid = $eid;
  $res->place  = $place;
  $res->points = _plm_rules_default_points($eid, $place);
  $res->cash   = _plm_rules_default_payout($eid, $place);
  return $res;
}

function _plm_result_row($result) {
  $row = array(
    _plm_format_place($result->place),
    l(t($result->name), 'plm/players/pid/' . $result->pid),
    $result->points,
    '$' . $result->cash,
  );   
  if (user_access('administer poker league')){
    $row[] = l(t('edit'), 'plm/results/' 
               . $result->eid . '/' . $result->place . '/edit');
  }
  return $row;
}

function theme_plm_event_results($event) {
  $eid = $event->eid;

  $results = _get_plm_results($eid);
  
  if (!$results && !user_access('administer poker league')){
    return '<p>No Results Posted</p>';
  }
  $header = array(
    'Place', 'Player', 'Points', '$$$',
  );
  if (user_access('administer poker league')){
    //$header[] = 'Operation';
    $header[] = '';
  }

  $num_places = $event->num_players;
  if ($num_places > 5) $num_places = 5;

  // Add up total prizepool
  $total = 0;

  // Format results in table
  for ($place=1;$place<=$num_places;$place++){
    $r = $results[$place];
    // display blank result for admin if not set
    if (!$results[$place]){
      $r = _plm_result_new($eid, $place);
    }
    $rows[] = _plm_result_row($r);
    $total += $r->cash;
  }
  
  $expected_pot_total = $event->pot_start + $event->buyin * $event->num_players;
  $rem = $expected_pot_total - $total;

  if ($rem) {
    $pre = '$';
    if ($rem > 0) $style = 'color: #006600';
    else {
      $style = 'color: #660000';
      // $-5 looks too weird...try ($5) instead
      $pre = '($';
      $rem = -$rem;
      $post = ')';
    }
    $lastrow = array(
      array('data' => 'Pot Remaining', 'header' => 1, 'colspan' => 3),
      array('data' => $pre . $rem . $post, 'style' => $style),
      array('data' => ''),
    );
    $rows[] = $lastrow;
  }
    
  if ($event->finished) {
    $caption = t('Final Results');
  }
  else {
    $caption = t('Tentative Results');
  }
  $output .= theme('table', $header, $rows, NULL, $caption);
  return $output;
}


function _theme_plm_table($header, $rows, $attributes = array(), $caption = NULL) {
  // Add sticky headers, if applicable.
  if (count($header)) {
    drupal_add_js('misc/tableheader.js');
    // Add 'sticky-enabled' class to the table to identify it for JS.
    // This is needed to target tables constructed by this function.
    $attributes['class'] = empty($attributes['class']) ? 'sticky-enabled' : ($attributes['class'] .' sticky-enabled');
  }

  $output = '<table'. drupal_attributes($attributes) .">\n";

  if (isset($caption)) {
    $output .= '<caption>'. $caption ."</caption>\n";
  }

  // Format the table header:
  if (count($header)) {
    $ts = plm_tablesort_init($header);
    // HTML requires that the thead tag has tr tags in it follwed by tbody
    // tags. Using ternary operator to check and see if we have any rows.
    $output .= (count($rows) ? ' <thead><tr>' : ' <tr>');
    foreach ($header as $cell) {
      $cell = plm_tablesort_header($cell, $header, $ts);
      $output .= _theme_table_cell($cell, TRUE);
    }
    // Using ternary operator to close the tags based on whether or not there are rows
    $output .= (count($rows) ? " </tr></thead>\n" : "</tr>\n");
  }
  else {
    $ts = array();
  }

  // Format the table rows:
  if (count($rows)) {
    $output .= "<tbody>\n";
    $flip = array('even' => 'odd', 'odd' => 'even');
    $class = 'even';
    foreach ($rows as $number => $row) {
      $attributes = array();

      // Check if we're dealing with a simple or complex row
      if (isset($row['data'])) {
        foreach ($row as $key => $value) {
          if ($key == 'data') {
            $cells = $value;
          }
          else {
            $attributes[$key] = $value;
          }
        }
      }
      else {
        $cells = $row;
      }
      if (count($cells)) {
        // Add odd/even class
        $class = $flip[$class];
        if (isset($attributes['class'])) {
          $attributes['class'] .= ' '. $class;
        }
        else {
          $attributes['class'] = $class;
        }

        // Build row
        $output .= ' <tr'. drupal_attributes($attributes) .'>';
        $i = 0;
        foreach ($cells as $cell) {
          $cell = plm_tablesort_cell($cell, $header, $ts, $i++);
          $output .= _theme_table_cell($cell);
        }
        $output .= " </tr>\n";
      }
    }
    $output .= "</tbody>\n";
  }

  $output .= "</table>\n";
  return $output;
}
